# flake8: noqa
"""(modulo cobranca e faturas)

Revision ID: 59475a5f2383
Revises: d0dd657436f0
Create Date: 2025-08-11 14:40:27.236459

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59475a5f2383"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = (
    "d0dd657436f0"  # pragma: allowlist secret
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
