# flake8: noqa
"""lembretes v1

Revision ID: b61771ffb247
Revises  # noqa: E402
Create Date: 2025-08-09 16:16:58.838874

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402

# revision identifiers, used by Alembic.
revision: str = "b61771ffb247"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
